contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #starter channel"
    url: https://nfcore.slack.com/channels/starter
    about: Discussion about the nf-core/starter pipeline
